controller:
  config:    
    server-tokens: "false" # requisito DISMA
  containerPort:
    https: 443
    http: 80
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-ilb-aks-pre-condorcloud"